<a class="headline" href="<?php echo $story->url ?>"><?php echo $story->headline ?></a> <br />
<span class="details">
    <?php echo $story->created_by ?> | <a href="/story/?id=<?php echo $story->id ?>"><?php echo $comment_count ?> Comments</a> | <?php echo date('n/j/Y g:i a', strtotime($story->created_on)) ?>
</span>

<?php if ($is_authenticated) : ?>
<form method="post" action="/comment/create">
    <input type="hidden" name="story_id" value="<?php echo $story->id ?>" />
    <textarea cols="60" rows="6" name="comment"></textarea><br />
    <input type="submit" name="submit" value="Submit Comment" />
</form>
<?php endif; ?>

<?php foreach ($comments as $comment) : ?>
<div class="comment">
    <span class="comment_details"><?php echo $comment['created_by'] ?> | <?php echo date('n/j/Y g:i a', strtotime($story->created_on)) ?> </span>
    <?php echo $comment['comment'] ?>
</div>
<?php endforeach; ?>
